EXEC ELRS.sde.set_current_version 'ELRS.Structures';

SELECT DOT_ID, COUNTY_ORDER, DIRECTION, COUNT(1)
FROM ELRS.elrs.LRSN_Milepoint_evw
WHERE (FROM_DATE IS NULL OR FROM_DATE <= CURRENT_TIMESTAMP) AND (TO_DATE IS NULL OR TO_DATE >= CURRENT_TIMESTAMP)
GROUP BY DOT_ID, COUNTY_ORDER, DIRECTION
HAVING COUNT(1)>1;

--SELECT ROUTE_ID, COUNT(DISTINCT CONCAT(DOT_ID, COUNTY_ORDER, DIRECTION))
--FROM ELRS.elrs.LRSN_Milepoint_evw
--WHERE (FROM_DATE IS NULL OR FROM_DATE <= CURRENT_TIMESTAMP) AND (TO_DATE IS NULL OR TO_DATE >= CURRENT_TIMESTAMP)
--GROUP BY ROUTE_ID
--HAVING COUNT(DISTINCT CONCAT(DOT_ID, COUNTY_ORDER, DIRECTION))>1;

--SELECT COUNT (DISTINCT CONCAT(DOT_ID, COUNTY_ORDER, DIRECTION)) FROM ELRS.elrs.LRSN_Milepoint_evw;
